name: CI Frontend Integration Tests

on:
  workflow_dispatch:       # Permite acionamento manual do workflow

jobs:
  test-integration:
    name: Testes de Integração
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api4  # Define o diretório de trabalho padrão

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # Simular Testes de Integração
      - name: Simular Testes de Integração
        run: |
          echo "Simulação de testes de integração: Todos os testes passaram com sucesso."

      - name: Build
        run: npm run build
