name: CI Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api4  # Define o diretório de trabalho padrão

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # Simular Testes Unitários
      - name: Simular Testes Unitários
        run: |
          echo "Simulação de testes unitários: Todos os testes passaram com sucesso."

      - name: Build
        run: npm run build

